### PR TITLE
Update readme to reflect the deprecation of "go get -u"

### PR DESCRIPTION
**Pull request by tjhowse**
See https://github.com/caddyserver/xcaddy/issues/7

### CODE REVIEW

**Review by mohammed90 — CHANGES_REQUESTED** [review]
Thank you for catching that and sending the PR! It's probably best to side-step having to track any changes by simply linking to the instructions on the xcaddy repo (https://github.com/caddyserver/xcaddy#install), and perhaps have a note asking the users to ensure `$(go env GOPATH)/bin` is in their path. The referenced paths can be different for different users and environments, so it's best if we do not assume. This way we don't need to instruct the users 

What do you think?

**Comment by tjhowse** [comment]
Finally got around to tidying this one up!

**Review by mholt — APPROVED** [review]
Beautiful. Thanks!

**Review by mohammed90 — APPROVED** [review]

**Pull request merged**
