### PR TITLE
Bump: go 1.21; caddy v2.7.6

### PR DESCRIPTION
**Pull request by IceCodeNew**

### CODE REVIEW

**Comment by IceCodeNew** [comment]
Motivation: I was getting errors while compiling my own caddy brew, and it seems pretty like the adapter plugins depend on something too old.
So here is the PR for bumping the dependencies, while also introducing a CI for checking whether the PR would break something, and a dependabot configuration so we can get help dealing with vulnerable dependencies.

image

**Comment by mohammed90** [comment]
> Motivation: I was getting errors while compiling my own caddy brew, and it seems pretty like the adapter plugins depend on something too old.
> So here is the PR for bumping the dependencies, while also introducing a CI for checking whether the PR would break something, and a dependabot configuration so we can get help dealing with vulnerable dependencies.
> 
> image

The error in the screenshot happened with the json-c adapter. Do you see the same with the nginx-adapter?

**Comment by IceCodeNew** [comment]
> The error in the screenshot happened with the json-c adapter. Do you see the same with the nginx-adapter?

Nah, I just do this PR out of courtesy. I am wondering if there are some vulnerabilities in the dependencies, so at least we should enable the dependabot for the security warning.
To go further, I tried to update the dependencies while introducing the dependabot.

P.S. I did the same thing to https://github.com/caddyserver/jsonc-adapter/pull/1 (which solved my problem)
and https://github.com/caddyserver/json5-adapter/pull/1 ;-)

**Comment by mohammed90** [comment]
Upgrading the Caddy version makes it impossible for users to build older caddy version with this module. The defined version in go.mod specifies the minimum version this module demands, but no maximum. We expect certain semantics of Caddy 2.7.0, so there's no need for upgrade. This reasoning doesn't work with dependabot, and I think dependabot is antithetical to how Go modules work. Thank you for the PR though!

For now, I upgraded the vulnerable deps to shut the scanner up.

**Pull request closed without merging**
